exclude: .*\.patch
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c59bba8fb259db0fec2bbb77ad8ba51ea7341b56  # frozen: v0.15.20
    hooks:
      - id: ruff-check
        args: [--fix, --show-fixes]
      - id: ruff-format
  - repo: https://github.com/reteps/dockerfmt
    rev: bf2867e6b3029c0cd40ba921a7f0b6547b9b8fe2  # frozen: v0.5.2
    hooks:
      - id: dockerfmt
        args: [--newline, --write]
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: 4380fbb73a154b5f5624794c1c78d9719ccc860f  # frozen: v2.16.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix, --trailing-commas]
      - id: pretty-format-yaml
        args: [--autofix, --offset, '2']
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 5030dca3047414c338091455ac41803200ec1f0f  # frozen: 0.37.3
    hooks:
      - id: check-github-workflows
      - id: check-renovate
  - repo: https://github.com/executablebooks/mdformat
    rev: 82912cdaea4fb830f751504486a7879c70526547  # frozen: 1.0.0
    hooks:
      - id: mdformat
  - repo: https://github.com/google/keep-sorted
    rev: 38613f5110f7fb5088d9ad68722e4018a11bc039  # frozen: v0.9.0
    hooks:
      - id: keep-sorted
  - repo: https://github.com/crate-ci/typos
    rev: 37bb98842b0d8c4ffebdb75301a13db0267cef89  # frozen: v1.47.2
    hooks:
      - id: typos
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
