#!/usr/bin/env python3
import datetime
import os
import struct
import sys
from pathlib import Path


# Rockchip rkbin's tools/boot_merger is a statically linked binary. It embeds
# the current wall-clock time in the loader header, so libfaketime cannot make
# its output reproducible. Public Rockchip boot_merger.c shows this field as
# rk_boot_header.releaseTime and writes it at byte offset 14 in the generated
# "LDR " image. The final four bytes are boot_merger's non-reflected CRC-32
# over the whole file before the CRC is appended.
#
# This script normalizes only that timestamp and then recomputes the trailing
# CRC. It was verified by comparing two independently generated loaders: they
# differed only in releaseTime minute/second bytes and the four CRC bytes; after
# running this script with the same SOURCE_DATE_EPOCH, the files were
# byte-identical. The CRC implementation was also checked against the original
# CRC trailers generated by boot_merger.
CRC32_POLY = 0x04C10DB7
RELEASE_TIME_OFFSET = 14
CRC_SIZE = 4


def rockchip_crc32(data: bytes) -> int:
    crc = 0
    for byte in data:
        crc ^= byte << 24
        for _ in range(8):
            if crc & 0x80000000:
                crc = ((crc << 1) ^ CRC32_POLY) & 0xFFFFFFFF
            else:
                crc = (crc << 1) & 0xFFFFFFFF
    return crc


def main() -> int:
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <rockchip-loader.bin>", file=sys.stderr)
        return 2

    source_date_epoch = os.environ.get("SOURCE_DATE_EPOCH")
    if not source_date_epoch:
        print("SOURCE_DATE_EPOCH is required", file=sys.stderr)
        return 2

    path = Path(sys.argv[1])
    data = bytearray(path.read_bytes())
    if data[:4] != b"LDR ":
        print(f"{path}: unsupported loader magic", file=sys.stderr)
        return 2
    if len(data) < RELEASE_TIME_OFFSET + 7 + CRC_SIZE:
        print(f"{path}: file is too small", file=sys.stderr)
        return 2

    timestamp = datetime.datetime.fromtimestamp(int(source_date_epoch), datetime.UTC)
    data[RELEASE_TIME_OFFSET : RELEASE_TIME_OFFSET + 7] = struct.pack(
        "<HBBBBB",
        timestamp.year,
        timestamp.month,
        timestamp.day,
        timestamp.hour,
        timestamp.minute,
        timestamp.second,
    )
    crc = rockchip_crc32(data[:-CRC_SIZE])
    data[-CRC_SIZE:] = struct.pack("<I", crc)
    path.write_bytes(data)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
